# Generated by Django 6.0.3 on 2026-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type_of_ministry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
