# Generated by Django 6.0.3 on 2026-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0002_alter_participant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host_pastor', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
