# Generated by Django 6.0.3 on 2026-03-14 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0005_finance_expense_category_finance_recorded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('vs_sports', 'VS Sports Game'), ('survival', 'Survival Game')], max_length=20)),
                ('game_type', models.CharField(choices=[('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('soccer', 'Soccer'), ('badminton', 'Badminton'), ('obstacle_challenge', 'Obstacle Challenge'), ('team_survival', 'Team Survival'), ('scavenger_hunt', 'Scavenger Hunt'), ('relay_race', 'Relay Race')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurvivalGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthcamp.activity')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthcamp.church')),
            ],
        ),
        migrations.CreateModel(
            name='VSGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_a_score', models.PositiveIntegerField(default=0)),
                ('church_b_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthcamp.activity')),
                ('church_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_games_as_team_a', to='youthcamp.church')),
                ('church_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_games_as_team_b', to='youthcamp.church')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vs_wins', to='youthcamp.church')),
            ],
        ),
    ]
