# Generated by Django 6.0.3 on 2026-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0006_activity_survivalgameresult_vsgameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivalgameresult',
            name='display_in_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vsgameresult',
            name='display_in_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
