# Generated by Django 6.0.3 on 2026-03-16 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0007_survivalgameresult_display_in_scoring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('violation_type', models.CharField(choices=[('late', 'Late Arrival'), ('misconduct', 'Misconduct'), ('rule_violation', 'Rule Violation'), ('unsportsmanlike', 'Unsportsmanlike Behavior'), ('equipment', 'Equipment Violation'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the violation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survival_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demerits', to='youthcamp.survivalgameresult')),
            ],
        ),
    ]
