# Generated by Django 6.0.3 on 2026-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0008_demerit'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color code for participant identification', max_length=7),
        ),
    ]
