# Generated by Django 6.0.3 on 2026-03-21 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0010_battleofbands_judgingcriteria_battleteam_battlescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleteam',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='battlescore',
            name='battle',
        ),
        migrations.AlterUniqueTogether(
            name='battlescore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='battlescore',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='battlescore',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='battlescore',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='battleteam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='battleteam',
            name='church',
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('merit_type', models.CharField(choices=[('excellent_performance', 'Excellent Performance'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership'), ('sportsmanship', 'Sportsmanship'), ('creativity', 'Creativity'), ('effort', 'Effort'), ('improvement', 'Improvement'), ('other', 'Other')], max_length=25)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the merit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('survival_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merits', to='youthcamp.survivalgameresult')),
            ],
        ),
        migrations.DeleteModel(
            name='BattleOfBands',
        ),
        migrations.DeleteModel(
            name='JudgingCriteria',
        ),
        migrations.DeleteModel(
            name='BattleScore',
        ),
        migrations.DeleteModel(
            name='BattleTeam',
        ),
    ]
