# Generated by Django 6.0.3 on 2026-03-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthcamp', '0011_remove_battleteam_battle_remove_battlescore_battle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('merit_type', models.CharField(max_length=25, choices=[
                    ('excellent_performance', 'Excellent Performance'),
                    ('teamwork', 'Teamwork'),
                    ('leadership', 'Leadership'),
                    ('sportsmanship', 'Sportsmanship'),
                    ('creativity', 'Creativity'),
                    ('effort', 'Effort'),
                    ('improvement', 'Improvement'),
                    ('other', 'Other'),
                ])),
                ('reason', models.TextField(blank=True, help_text='Optional reason for merit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True)),
                ('survival_result', models.ForeignKey('youthcamp.survivalgameresult', on_delete=models.CASCADE, related_name='merits')),
            ],
        ),
    ]
